### ISSUE TITLE
Checking for updates?

### ISSUE THREAD

**Issue by nikorue** [Braasileiro/DeezerRPC#13]
as the title says, can you add an ability to check for updates and/or add version info to the app itself?

**Comment by Braasileiro** [comment]
It's already been implemented in 1.0.3, it's automatically checked when opening the app.

On Windows, you can see the current version by clicking on the icon in the taskbar.
On Linux/Mac you can see the current version in "About" located in the global menu or something like that.

Check this commit: 70f541f6c67f6d83a6714a81c5f4fafff8e93514
