### ISSUE TITLE
Deezer controls plugin

### ISSUE THREAD

**Issue by nikorue** [Braasileiro/DeezerRPC#15]
if you ever followed, there's a betterdiscord(trash) and powercord(gut) controls for spotify, one(trash) uses tos breaking controls on device, while the other(gut) uses actual spotify api to control spotify playing now, is it possible to implement any of that as a plugin for either of those?

**Comment by Braasileiro** [comment]
RPC api has limitations for normal users, spotify works differently. So I don't know if it's possible to do that. I have never used any of these plugins either.
