### ISSUE TITLE
Aceita Contribuição?

### ISSUE THREAD

**Issue by TheoOliveira** [Braasileiro/DeezerRPC#16]
Só checando se tu aceita ajuda no projeto. Como não tem nada no README fiquei na dúvida.

**Comment by Braasileiro** [comment]
Então, eu não tenho muito tempo para mexer nesse projeto, normalmente só atualizo quando encontro algum bug ou consigo algum tempo, e por esse motivo que não mencionei sobre contribuições no readme. Mas obrigado pelo interesse, eu comecei esse projeto mais pra algo pessoal do que distribuir pro público, só aproveitei que funcionou ok e coloquei aqui no GitHub.
