### ISSUE TITLE
Lot of cpu usage even when closed

### ISSUE THREAD

**Issue by Tainted06** [Braasileiro/DeezerRPC#17]
Deezer RPC isn't on and isn't open in the task bar, but its still using ~15% of my cpu

Not sure if this is an issue, but I don't think its normal 

![task manager img](https://cdn.upload.systems/uploads/5fdLkcIT.png)
*task manager img*

![task bar img](https://cdn.upload.systems/uploads/SYjnQ6Fa.png)
*task bar img*

![showing that deezer isnt open](https://cdn.upload.systems/uploads/RJo2TOUY.png)
*showing that deezer isnt open*

**Comment by Braasileiro** [comment]
Has this happened more than once? And which version are you using? I tried to replicate, but it didn't happen to me. If the process is minimized to notification area, normally they appear on 'Background processes' or on 'Details'.

It's good to check if the antivirus is interfering with something, and add the application folder to the exclusion list.

**Comment by Tainted06** [comment]
Weird its not happening again, it might have just been a 1 time thing, or an antivirus messing with it.

Anyways thanks for the help.
