### ISSUE TITLE
Add minimize to tray and normal Deezer icon?

### ISSUE THREAD

**Issue by vleeuwenmenno** [Braasileiro/DeezerRPC#2]
I made a client too but this one seems to work smoother. The only thing I am missing is a proper Deezer icon and hiding the window to a tray icon.

**Comment by Braasileiro** [comment]
I will try to do that next week. 👍

**Comment by vleeuwenmenno** [comment]
I managed to add it to my own version. If you want I can later make a PR to this repo.

**Comment by Braasileiro** [comment]
> I managed to add it to my own version. If you want I can later make a PR to this repo.

I would appreciate it! :)
