### ISSUE TITLE
Can you add interact with system-wide media player?

### ISSUE THREAD

**Issue by KontraproduktivK** [Braasileiro/DeezerRPC#21]
I wish a interaction with system wide media player popup by win10

**Comment by Braasileiro** [comment]
I'm already planning something like that for the next release, when I have time to work on the project I'll probably be implementing it.

**Comment by ian70203** [comment]
+1ing this, as my Surface Pro keyboard only has play/pause and I usually rely on the system wide controls to skip tracks.

**Comment by Braasileiro** [comment]
I'm trying to use [NodeRT](https://github.com/NodeRT/NodeRT) for implementation, but I'm not able to compile. I will look for another way to do this.
