### ISSUE TITLE
Songs with multiple artists only show first artist

### ISSUE THREAD

**Issue by ian70203** [Braasileiro/DeezerRPC#22]
Hi, I've been using DeezerRPC for the past few days now and I really enjoy using it to show what song I'm listening to on Discord.
I noticed that on songs with multiple artists (or, in this case, artist and singer) only show the first artist on Rich Presence. An example is linked below.
![image](https://user-images.githubusercontent.com/10983868/147294108-1c5ab967-20dc-4e8f-8498-2dd29aae41e6.png)
I don't know if there is a limitation on how long the artist line can be, so it might not be possible to show all artists on every song. Possibly, if the artist line is running up against the text limit, maybe the artist's name could be truncated?

Thanks,
grizzogor

**Comment by Braasileiro** [comment]
I'll take a look at this, maybe has an array of names.

**Comment by Braasileiro** [comment]
Implemented in [1.0.7](https://github.com/Braasileiro/DeezerRPC/releases/tag/1.0.7) release.
