### ISSUE TITLE
Idea : add back/forward buttons or keyboard shortcuts

### ISSUE THREAD

**Issue by AntoineTurmel** [Braasileiro/DeezerRPC#28]
Win/Linux:  Alt+LeftArrow for Back and Alt+RightArrow for Forward
Mac:       Cmd+LeftArrow for Back and Cmd+RightArrow for Forward

It would be nice since Deezer app doesn't have them and the web version allow this using web browser.

**Comment by Braasileiro** [comment]
Sorry for the very late response.
This feature has already implemented by faejr and is merged in the main branch, I just don't have much time to work on my personal projects lately.

**Comment by AntoineTurmel** [comment]
Oh nice work @faejr !
I did compile the project, it's working but I assume the arrow need to be white when it's in dark mode 👍 
![image](https://user-images.githubusercontent.com/119288/172212869-48bd92cf-f5a1-49c4-aab6-4b37bc589e7c.png)

Other issues I ran into (with master) :
``` • default Electron icon is used  reason=application icon is not set```

![image](https://user-images.githubusercontent.com/119288/172213455-f659c04a-f806-441e-b89f-2e576502e81a.png)

**Comment by faejr** [comment]
That's strange, when I first implemented it I specifically made sure it'd change colour depending on dark and lightmode. I guess something might've happened along the way
