### ISSUE TITLE
Discord Rich Presence não está funcionando no Windows 11

### ISSUE THREAD

**Issue by DvoraNoob** [Braasileiro/DeezerRPC#32]
Como vi que você é BR vou escrever em português mesmo.

Então aparentemente não mostra o que está tocando no discord no Windows 11, não sei se foi erro meu, ou é do programa.

Eu instalei a última versão, fiz o login enquanto o discord estava aberto, e mesmo assim não aparece no discord, eu já reiniciei o PC e nada também

**Comment by DvoraNoob** [comment]
Já achei o problema, tinha que ativar o status da atividade.

**Comment by Braasileiro** [comment]
> Já achei o problema, tinha que ativar o status da atividade.

Isso acontece bastante. 😄
Obrigado por ter dado um feedback depois.

**Comment by DvoraNoob** [comment]
> > Já achei o problema, tinha que ativar o status da atividade.
> 
> Isso acontece bastante. 😄 Obrigado por ter dado um feedback depois.

Eu até tentei editar seu código, mas não entendi muito bem a parte do DOM, eu estava tentando colocar as imagens, mas descobri que não dá para usar url se não for empresa confiável, também achei um bug, os botões de mídia não funcionam com um jogo aberto.
